### ISSUE TITLE
License

### ISSUE THREAD

**Issue by markusb** [mirdej/udmx#6]
What is the license for this project ?

I just got pinged on a fork I made ages ago and published on Github (before udmx was moved over from Google code) because I did not specify a license. See https://github.com/markusb/uDMX-linux/issues/2

As my code just is a fork, I can not really set a license without first cnsultion the license of the original.

**Comment by mirdej** [comment]
Hello Markus

as noted in udmx.c the original license is GPL 2.0
> /*
>     udmx.c
>     
>     Max-Interface to the [ a n y m a | usb-dmx-interface ]
>     
>     Authors:    Max & Michael Egger
>     Copyright:    2006-2015 [ a n y m a ]
>     Website:    www.anyma.ch
>     
>     License:    GNU GPL 2.0 www.gnu.org
>     
>     Version:    2015-11-09
>  */


hope this helps
Michael

**Comment by markusb** [comment]
Great, thanks Michael!

So I'll assign GPL 2.0 to my project and all is well.
